version: '3'

services:
    db:
       container_name: db
       image: postgres
       restart: always
       environment:
              POSTGRES_USER: root
              POSTGRES_PASSWORD: root
              POSTGRES_DB: db
       volumes:
           - ./postgres-data:/var/lib/postgresql/data
       ports:
           - "5432:5432"

    pgadmin:

          image: dpage/pgadmin4
          restart: always
          environment:
                PGADMIN_DEFAULT_EMAIL: smits1893@gmail.com
                PGADMIN_DEFAULT_PASSWORD: root
          ports:
            - "5050:80"
          depends_on:
              - db